NAME=miniforge3

CONDA_VERSION=24.9.2-0
MODULE_HIDDEN=false

VERSION=$(CONDA_VERSION)
DOWNLOAD_TARGET_FILE=Miniforge3-$(CONDA_VERSION)-Linux-x86_64.sh
CONFIG=false
BUILD=false
INSTALL_TARGET_FILE=bin/conda
