NAME=miniconda3

#CONDA_VERSION=4.12.0
CONDA_VERSION=23.3.1-0
PYTHON_VERSION=py39

#CONDA_VERSION=22.11.1-1
#CONDA_VERSION=23.3.1-0
#PYTHON_VERSION=py310
#MODULE_HIDDEN=true

VERSION=$(CONDA_VERSION)-$(PYTHON_VERSION)
DOWNLOAD_TARGET_FILE=Miniconda3-$(PYTHON_VERSION)_$(CONDA_VERSION)-Linux-x86_64.sh
CONFIG=false
BUILD=false
INSTALL_TARGET_FILE=bin/conda

