NAME=miniconda3

## Source: https://repo.anaconda.com/miniconda/
#CONDA_VERSION=4.12.0
#CONDA_VERSION=22.11.1-1
CONDA_VERSION=23.3.1-0
PYTHON_VERSION=py39
PYTHON_VERSION=py310
MODULE_HIDDEN=true

CONDA_VERSION=23.5.2-0
PYTHON_VERSION=py39
PYTHON_VERSION=py310
PYTHON_VERSION=py311
MODULE_HIDDEN=false

CONDA_VERSION=23.11.0-2
PYTHON_VERSION=py39
PYTHON_VERSION=py310
PYTHON_VERSION=py311
MODULE_HIDDEN=false

CONDA_VERSION=24.1.2-0
PYTHON_VERSION=py39
PYTHON_VERSION=py310
PYTHON_VERSION=py311
PYTHON_VERSION=py312
MODULE_HIDDEN=false

VERSION=$(CONDA_VERSION)-$(PYTHON_VERSION)
DOWNLOAD_TARGET_FILE=Miniconda3-$(PYTHON_VERSION)_$(CONDA_VERSION)-Linux-x86_64.sh
CONFIG=false
BUILD=false
INSTALL_TARGET_FILE=bin/conda

