NAME=pindel
VERSION:=0.2.5b8
URL_DOWNLOAD=https://github.com/genome/pindel/releases
URL=https://www.sanger.ac.uk/science/tools/pindel
DOWNLOAD_TARGET_FILE=INSTALL
CONFIG=false
BUILD_TARGET_FILE=pindel
INSTALL_TARGET_FILE=pindel
WARNING="This software is built with rpath, i.e. it needs to be rebuilt if its installation path changed"
