include config.mk
include ../utils.mk

TARBALL=$(NAME)-$(VERSION).tgz

## ----------------------------------------------------------
## SOFTWARE
## ----------------------------------------------------------
$(DOWNLOAD_TARGET):
	mkdir -p $(BUILD_HOME); \
	cd $(BUILD_HOME); \
	curl -L -O https://github.com/qtop/${NAME}/archive/v${VERSION}.tar.gz; \
	tar xfz v${VERSION}.tar.gz

$(CONFIG_TARGET): $(DOWNLOAD_TARGET)
	cd $(BUILD_PATH); \
	cp Makefile Makefile.org; \
	sed 's|^prefix = /usr|prefix = $(PREFIX)|' Makefile.org > Makefile
	touch $@
