-- /usr/share/lmod/lmod/libexec/sh_to_modulefile /opt/rh/devtoolset-4/enable
setenv("INFOPATH","/opt/rh/devtoolset-4/root/usr/share/info")
setenv("JAVACONFDIRS","/opt/rh/devtoolset-4/root/etc/java:/etc/java")
prepend_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-4/root/usr/lib")
prepend_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-4/root/usr/lib64")
prepend_path("MANPATH","/opt/rh/devtoolset-4/root/usr/share/man")
prepend_path("PATH","/opt/rh/devtoolset-4/root/usr/bin")
setenv("PCP_DIR","/opt/rh/devtoolset-4/root")
setenv("PERL5LIB","/opt/rh/devtoolset-4/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-4/root/usr/lib/perl5:/opt/rh/devtoolset-4/root//usr/share/perl5/vendor_perl")
prepend_path("PYTHONPATH","/opt/rh/devtoolset-4/root/usr/lib/python2.7/site-packages")
prepend_path("PYTHONPATH","/opt/rh/devtoolset-4/root/usr/lib64/python2.7/site-packages")
setenv("XDG_CONFIG_DIRS","/opt/rh/devtoolset-4/root/etc/xdg:/etc/xdg")
setenv("XDG_DATA_DIRS","/opt/rh/devtoolset-4/root/usr/share:/usr/local/share:/usr/share")
