-- /usr/share/lmod/lmod/libexec/sh_to_modulefile /opt/rh/devtoolset-7/enable
setenv("INFOPATH","/opt/rh/devtoolset-7/root/usr/share/info")
prepend_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-7/root/usr/lib/dyninst")
prepend_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-7/root/usr/lib64/dyninst")
prepend_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-7/root/usr/lib")
prepend_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-7/root/usr/lib64")
append_path("LD_LIBRARY_PATH","/opt/rh/devtoolset-7/root/usr/lib")
append_path("LD_LIBRARY_PATH","/usr/lib64/openmpi/lib")
prepend_path("MANPATH","/opt/rh/devtoolset-7/root/usr/share/man")
prepend_path("PATH","/opt/rh/devtoolset-7/root/usr/bin")
setenv("PCP_DIR","/opt/rh/devtoolset-7/root")
setenv("PERL5LIB","/opt/rh/devtoolset-7/root//usr/lib64/perl5/vendor_perl:/opt/rh/devtoolset-7/root/usr/lib/perl5:/opt/rh/devtoolset-7/root//usr/share/perl5/vendor_perl")
prepend_path("PYTHONPATH","/opt/rh/devtoolset-7/root/usr/lib/python2.7/site-packages")
prepend_path("PYTHONPATH","/opt/rh/devtoolset-7/root/usr/lib64/python2.7/site-packages")
