NAME=easycatfs
VERSION:=0.1.2
DOWNLOAD_TARGET_FILE=bin/$(NAME)
CONFIG=false
BUILD_TARGET_FILE=bin/catfs
INSTALL_TARGET_FILE=bin/$(NAME)
SOFTWARE_HOME=$(SOFTWARE_ROOT_CBI_TESTING)
MODULE_HOME=$(MODULE_ROOT_CBI_TESTING)
