on: [push, pull_request]

name: luacheck

jobs:
  checks:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    
    runs-on: ubuntu-latest
    
    name: luacheck

    strategy:
      fail-fast: false
      
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
      
    - name: Install Lua
      uses: leafo/gh-actions-lua@v11

    - name: Install dependencies
      run: |
        lua -v
        luac -v

    - name: Check *.lua
      run: |
        make check.lua

    - name: Check *.lua.tmpl
      run: |
        make check.lua.tmpl
